const ABILITY_TEST_CONTEXT = `
It was a rainy Friday afternoon when Cindy, Jerry, Mary, and David gathered at their favorite campus coffee shop. What started as a casual chat about their weekend plans quickly evolved into a deep philosophical debate about the true meaning of friendship and what makes a relationship last a lifetime.

"I still believe that honesty is the bedrock of any meaningful connection," Cindy began, taking a sip of her latte. "A good friend should be completely transparent. To me, trust is the absolutely essential foundation. A true friend is someone who isn't afraid to tell you the truth, even when it is incredibly hard to hear or might cause temporary discomfort. They shouldn't sugarcoat things or agree with you just to keep the peace. For instance, if I am making a terrible career decision or dating someone toxic, I expect my friend to call me out on it privately. However, they must also be the one defending me fiercely in public. Honesty builds mutual respect, and without respect, a friendship is just a superficial acquaintance."

Jerry shook his head slightly, laughing. "That is a fair point, Cindy, and I do not disagree, but for me, loyalty and a shared sense of humor take the crown. You can have an honest friend who abandons you when things get tough. A good friend is someone who sticks by your side through thick and thin, especially during the darkest and most challenging moments of your life. The world is demanding enough as it is. Having a friend who knows exactly how to make you laugh and helps you forget your troubles is invaluable. Furthermore, shared experiences—whether it is surviving a difficult university project or just talking about random things until 3 AM—build a bond that is hard to break. Loyalty means I know you have my back, no matter what rumors are spreading."

Mary, who had been listening intently, gently placed her mug on the table. "I completely agree with both of you on trust and loyalty, but I would like to add empathy and active listening to the top of the list. In my opinion, a good friend is someone who provides a safe, non-judgmental space for you to express your deepest feelings. Sometimes, we don't need advice, logical solutions, or someone to 'fix' our problems; we just need someone who will sit with us in the silence, listen attentively, and validate our emotions. Emotional support and understanding are what truly deepen a friendship over time. If a friend cannot understand my emotional needs, all the honesty and humor in the world will not make me feel less lonely."

David leaned forward, adjusting his glasses. "You all make excellent points, but you are missing a crucial element: mutual growth and accountability. We are not the same people we were five years ago, and we shouldn't be. A great friend is a catalyst for your personal development. They challenge you to be the best version of yourself, intellectually and professionally. If I am slacking off on my goals or settling for mediocrity, a true friend pushes me to strive for more. They celebrate my successes without jealousy and inspire me by pursuing their own ambitions. Friendship shouldn't just be a comfort zone; it should be an environment that fosters continuous growth."

The group fell silent for a moment, absorbing the different perspectives. Ultimately, while their priorities differed—Cindy valuing unvarnished honesty, Jerry prioritizing unwavering loyalty, Mary emphasizing deep empathy, and David focusing on mutual growth—they realized that these traits were not mutually exclusive. Instead, they form the intricate puzzle pieces of a lifelong relationship. A meaningful friendship requires mutual effort, consistency, genuine care, and the willingness to adapt to each other's evolving needs.
`;

module.exports = ABILITY_TEST_CONTEXT;